#!/bin/bash
## Creates a Player
##
## Usage:
##  $0 {player name}
##

if [ $# == 0 ]
then
    usage $0
    exit 0
fi

for name in $*
do
    curl -i -X POST -H "Content-Type:application/json" -d \
    '{"name":"'$name'"}' \
    localhost:8080/players
done

